goog.addDependency("base.js", ['goog'], []);
goog.addDependency("../cljs/core.js", ['cljs.core'], ['goog.string', 'goog.array', 'goog.object', 'goog.string.StringBuffer']);
goog.addDependency("../cljs_pong/math.js", ['cljs_pong.math'], ['cljs.core']);
goog.addDependency("../cljs_pong/config.js", ['cljs_pong.config'], ['cljs.core']);
goog.addDependency("../cljs_pong/paddle.js", ['cljs_pong.paddle'], ['cljs_pong.math', 'cljs.core', 'cljs_pong.config']);
goog.addDependency("../dommy/utils.js", ['dommy.utils'], ['cljs.core']);
goog.addDependency("../clojure/string.js", ['clojure.string'], ['cljs.core', 'goog.string', 'goog.string.StringBuffer']);
goog.addDependency("../dommy/attrs.js", ['dommy.attrs'], ['cljs.core', 'dommy.utils', 'clojure.string']);
goog.addDependency("../cljs_pong/keyhandler.js", ['cljs_pong.keyhandler'], ['cljs.core']);
goog.addDependency("../cljs_pong/ball.js", ['cljs_pong.ball'], ['cljs_pong.math', 'cljs.core', 'cljs_pong.config']);
goog.addDependency("../cljs_pong/game.js", ['cljs_pong.game'], ['cljs_pong.math', 'cljs.core', 'cljs_pong.ball', 'cljs_pong.paddle', 'cljs_pong.config']);
goog.addDependency("../dommy/template.js", ['dommy.template'], ['dommy.attrs', 'cljs.core', 'dommy.utils', 'clojure.string']);
goog.addDependency("../dommy/core.js", ['dommy.core'], ['dommy.attrs', 'cljs.core', 'dommy.template', 'dommy.utils', 'clojure.string']);
goog.addDependency("../cljs_pong/draw.js", ['cljs_pong.draw'], ['cljs.core', 'dommy.utils', 'cljs_pong.config', 'dommy.core']);
goog.addDependency("../cljs_pong/core.js", ['cljs_pong.core'], ['cljs.core', 'cljs_pong.draw', 'cljs_pong.game', 'cljs_pong.keyhandler', 'dommy.core']);